<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE colHAREM [

<!ELEMENT colHAREM (DOC)*>
<!ATTLIST colHAREM
  versao CDATA #REQUIRED>

<!ELEMENT DOC (#PCDATA|ALT|EM|OMITIDO|P)*> <!ATTLIST DOC DOCID CDATA #REQUIRED>

<!ELEMENT P (#PCDATA|ALT|EM|OMITIDO)*>

<!ELEMENT ALT (#PCDATA|EM|OMITIDO)*>

<!ELEMENT EM (#PCDATA)>
<!ATTLIST EM
  ID CDATA #REQUIRED
  CATEG CDATA #IMPLIED
  TIPO CDATA #IMPLIED
  SUBTIPO CDATA #IMPLIED
  COMENT CDATA #IMPLIED
  TIPOREL CDATA #IMPLIED
  COREL CDATA #IMPLIED
  TEMPO_REF (ENUNCIACAO|TEXTUAL) #IMPLIED
  SENTIDO (ANTERIOR|POSTERIOR|SIMULT|ANTERIOR_OU_SIMUL|POSTERIOR_OU_SIMULT) #IMPLIED
  VAL_DELTA CDATA #IMPLIED
  VAL_NORM CDATA #IMPLIED>

<!ELEMENT OMITIDO (#PCDATA|EM)*>
]>

<colHAREM versao="PrimeiroHAREM-primeiroevento-5.0-semTEMPO">
<DOC DOCID="HAREM-871-07800">
<EM ID="0" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Abraço</EM> Página Principal
<EM ID="1" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">ASSOCIAÇÃO DE APOIO A PESSOAS COM VIH/SIDA</EM>
A <EM ID="2" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">ABRAÇO</EM> é uma <EM ID="3" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Instituição Particular de Solidariedade Social</EM>. Organização não governamental sem fins lucrativos de prestação de serviços
na área da <EM ID="4" CATEG="ABSTRACCAO" TIPO="ESTADO">SIDA</EM>.
Foi constituída por escritura pública em <EM ID="5" CATEG="TEMPO" TIPO="DATA">Junho de 1992</EM>, formalizando e dando continuidade ao trabalho de um pequeno número de voluntários
que, desde <EM ID="6" CATEG="TEMPO" TIPO="DATA">Dezembro de 1991</EM>, prestava apoio psicológico, social e material a seropositivos internados na <EM ID="7" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Unidade de Doenças Infecciosas e Parasitárias do Hospital Egas Moniz</EM>, e tentava melhorar as condições hospitalares.
Os objectivos da <EM ID="8" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Associação</EM> são :
Apoio a pessoas afectadas pelo <EM ID="9" CATEG="ABSTRACCAO" TIPO="ESTADO">VIH/SIDA</EM>;
Apoio, treino e formação de trabalhadores e técnicos de saúde envolvidos com o <EM ID="10" CATEG="ABSTRACCAO" TIPO="ESTADO">VIH</EM>;
Prevenção da infecção, dirigida à população em geral e, especialmente, aos jovens, utilizadores de droga, trabalhadores do sexo, mulheres, gays, trangenders e reclusos;
Luta contra a discriminação e defesa dos direitos das pessoas infectadas.
A <EM ID="11" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Associação</EM> dispõe de uma estrutura de cerca de vinte assalariados sendo portanto a sua actividade desenvolvida essencialmente através de voluntários. A sua acção tem âmbito nacional, dispondo de três centros de trabalho na área da grande <EM ID="12" CATEG="LOCAL" TIPO="HUMANO">Lisboa</EM>, um no <EM ID="13" CATEG="LOCAL" TIPO="HUMANO">Porto</EM>, aberto em <EM ID="14" CATEG="TEMPO" TIPO="DATA">Dezembro de 1994</EM>, e um no <EM ID="15" CATEG="LOCAL" TIPO="HUMANO">Funchal</EM>, aberto em <EM ID="16" CATEG="TEMPO" TIPO="DATA">Dezembro de 1995</EM>.
A <EM ID="17" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Associação</EM> está organizada por núcleos e delegações regionais, cada um deles reportando a um dos três membros da <EM ID="18" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Comissão Executiva</EM>. Actualmente a <EM ID="19" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Associação</EM> conta com <EM ID="20" CATEG="VALOR" TIPO="QUANTIDADE">cerca de 460</EM> sócios e <EM ID="21" CATEG="VALOR" TIPO="QUANTIDADE">650</EM> voluntários; destes, <EM ID="22" CATEG="VALOR" TIPO="QUANTIDADE">70</EM> trabalham connosco numa base regular e permanente.
</DOC>
<DOC DOCID="HAREM-361-02413">
<EM ID="23" CATEG="PESSOA" TIPO="INDIVIDUAL">Fernando Ferreira</EM>
[click for a page in english]
<EM ID="24" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">CMAF</EM>- <EM ID="25" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Universidade de Lisboa</EM> <EM ID="26" CATEG="LOCAL" TIPO="HUMANO">Gabinete A2-31 Avenida Professor Gama Pinto, 2</EM> Telefone do Gabinete: 217904893 P-1649-003 <EM ID="28" CATEG="LOCAL" TIPO="HUMANO">Lisboa</EM> Extensão interna: 4293 <EM ID="30" CATEG="LOCAL" TIPO="HUMANO">Portugal</EM> Email: ferferr@cii.fc.ul.pt <EM ID="32" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Departamento de Matemática</EM> | <EM ID="33" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Faculdade de Ciências</EM> | <EM ID="34" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Universidade de Lisboa</EM> | <EM ID="35" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">CMAF</EM>
Apresentação
Bem vindos àminha página pessoal. Sou <EM ID="36" CATEG="PESSOA" TIPO="CARGO">Professor Associado</EM> do <EM ID="37" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Departamento de Matemática da Universidade de Lisboa</EM> e membro do <EM ID="38" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Centro de Matemática e Aplicações Fundamentais</EM> - <EM ID="39" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">CMAF</EM>. Clique aqui para obter o meu CV.
Interesses Académicos
<EM ID="40" CATEG="ABSTRACCAO" TIPO="DISCIPLINA">Lógica Matemática</EM>, em especial teorias fracas da aritmética e da análise. <EM ID="41" CATEG="ABSTRACCAO" TIPO="DISCIPLINA">Filosofia</EM>  e <EM ID="42" CATEG="ABSTRACCAO" TIPO="DISCIPLINA">Fundamentos de Matemática</EM> . Tenho um interesse amador (no sentido latino da palavra) por alguns problemas da <EM ID="43" CATEG="ABSTRACCAO" TIPO="DISCIPLINA">Filosofia Antiga</EM> , particularmente no problema da falsidade em <EM ID="44" CATEG="ABSTRACCAO" TIPO="OBRA">Parménides</EM> e <EM ID="45" CATEG="ABSTRACCAO" TIPO="OBRA">Platão</EM>. Também escrevi alguns ensaios expositórios sobre temas da lógica: clique aqui para os ver.
Ensino
No presente semestre dou aulas teórico-práticas de <EM ID="46" CATEG="ABSTRACCAO" TIPO="DISCIPLINA">Álgebra 2</EM>, cadeira do segundo ano das licenciaturas em <EM ID="47" CATEG="ABSTRACCAO" TIPO="DISCIPLINA">Matemática</EM>. O <EM ID="48" CATEG="PESSOA" TIPO="INDIVIDUAL">Professor José Perdigão Dias da Silva</EM> éo regente da cadeira.
No semestre passado fui responsável pelas cadeiras de <EM ID="49" CATEG="ABSTRACCAO" TIPO="DISCIPLINA">Topologia</EM> e <EM ID="50" CATEG="ABSTRACCAO" TIPO="DISCIPLINA">Introdução àAnálise Funcional</EM>, do terceiro ano das licenciaturas em <EM ID="51" CATEG="ABSTRACCAO" TIPO="DISCIPLINA">Matemática</EM>, e de <EM ID="52" CATEG="ABSTRACCAO" TIPO="DISCIPLINA">Teoria da Demonstração</EM>, do 
Mestrado em <EM ID="53" CATEG="ABSTRACCAO" TIPO="DISCIPLINA">Matemática</EM>.
No ano passado ensinei a cadeira de <EM ID="54" CATEG="ABSTRACCAO" TIPO="DISCIPLINA">Lógica Matemática</EM> aos finalistas de <EM ID="55" CATEG="ABSTRACCAO" TIPO="DISCIPLINA">Matemática</EM> e licenciaturas relacionadas. Clique aqui para
ver a página desta cadeira. Também dei a cadeira <EM ID="56" CATEG="ABSTRACCAO" TIPO="DISCIPLINA">Lógica de Primeira-Ordem</EM> ao primeiro ano das licenciaturas em <EM ID="57" CATEG="ABSTRACCAO" TIPO="DISCIPLINA">Informática</EM> e <EM ID="58" CATEG="ABSTRACCAO" TIPO="DISCIPLINA">Engenharia da Linguagem e do Conhecimento</EM>. A página web desta cadeira ainda se encontra disponível on-line em html://www.alf1.cii.fc.ul.pt/~ferferr/lpo.html.
Também colaboro no Mestrado em <EM ID="60" CATEG="ABSTRACCAO" TIPO="DISCIPLINA">Filosofia da Linguagem e da Consciência</EM> da <EM ID="61" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Faculdade de Letras</EM>.
Eventos
De <EM ID="62" CATEG="TEMPO" TIPO="DATA">25</EM> a <EM ID="63" CATEG="TEMPO" TIPO="DATA">28 de Junho</EM> decorrerá em <EM ID="64" CATEG="LOCAL" TIPO="HUMANO">Lisboa</EM>, no <EM ID="65" CATEG="LOCAL" TIPO="HUMANO">CMAF</EM>, a <EM ID="66" CATEG="ACONTECIMENTO" TIPO="ORGANIZADO">School on Real Algebraic and Analytic Geometry and O-minimal Structures</EM> .
Às quintas-feiras decorre o <EM ID="67" CATEG="ACONTECIMENTO" TIPO="ORGANIZADO">Seminário de Lógica Matemática</EM> (<EM ID="68" CATEG="ACONTECIMENTO" TIPO="ORGANIZADO">SLM</EM>), organizado por mim e pelo <EM ID="69" CATEG="PESSOA" TIPO="INDIVIDUAL">Professor Narciso Garcia</EM> do <EM ID="70" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Instituto Superior Técnico</EM>. Se quiser ter notícias regulares sobre o <EM ID="71" CATEG="ACONTECIMENTO" TIPO="ORGANIZADO">SLM</EM>, por favor contacte-me.
Vária
Sou co-editor da <EM ID="72" CATEG="OBRA" TIPO="REPRODUZIDA">Disputatio</EM> , uma revista de <EM ID="73" CATEG="ABSTRACCAO" TIPO="DISCIPLINA">Filosofia Analítica</EM>.
</DOC>
<DOC DOCID="HAREM-281-01176">
<EM ID="74" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">BOMBEIROS VOLUNTÁRIOS DE VILA NOVA DE OLIVEIRINHA</EM>
Clique aqui para ENTRAR NO MENU
(Fotografia do Quartel Construído em <EM ID="75" CATEG="TEMPO" TIPO="DATA">1935</EM>)
CLIQUE AQUI para enviar uma mensagem
Visitas desde <EM ID="76" CATEG="TEMPO" TIPO="DATA">13/05/2001</EM>
Mensagem do <EM ID="77" CATEG="PESSOA" TIPO="CARGO">Presidente da Direcção</EM>
Caros amigos dos <EM ID="78" CATEG="PESSOA|ORGANIZACAO" TIPO="GRUPOMEMBRO|INSTITUICAO">Bombeiros</EM>:
A nossa página na <EM ID="79" CATEG="LOCAL" TIPO="VIRTUAL">Internet</EM> já está activa desde o dia <EM ID="80" CATEG="TEMPO" TIPO="DATA">13 de Maio de 2001</EM>, data em que se comemorou mais uma <EM ID="81" CATEG="ACONTECIMENTO" TIPO="ORGANIZADO">Festa dos Carolos</EM> (<EM ID="82" CATEG="TEMPO" TIPO="DATA">2001</EM>) .
A <EM ID="83" CATEG="ACONTECIMENTO" TIPO="ORGANIZADO">Festa dos Carolos</EM>é uma tradição desta terra que os <EM ID="84" CATEG="PESSOA|ORGANIZACAO" TIPO="GRUPOMEMBRO|INSTITUICAO">Bombeiros</EM> querem manter viva neste começo do novo milénio.
E como nesta nova era as solicitações são diversas, os <EM ID="85" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Bombeiros Voluntários de Vila Nova de Oliveirinha</EM> têm bem presente os novos desafios.
Assim, paralelamente à construção do Novo Quartel dos Bombeiros --temos dado passos bastante importantes!--, vamos continuar a melhorar esta página na <EM ID="86" CATEG="LOCAL" TIPO="VIRTUAL">Internet</EM>.
Continuamos a receber conteúdos para dotarmos esta página com bastante informação, pelo que a vossa ajuda pode ser determinante. Para tal,
podem escrever-nos, enviar um fax ou uma mensagem via correio electrónico. Para isso, visite a página de CONTACTOS .
Vamos todos ajudar os <EM ID="87" CATEG="PESSOA|ORGANIZACAO" TIPO="GRUPOMEMBRO|INSTITUICAO">Bombeiros</EM>.
Vamos todos divulgar aquilo que é este corpo, o <EM ID="88" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Corpo dos Bombeiros Voluntários de V. Nova de Oliveirinha</EM>.
Caros amigos, fiquem pois atentos às actualizações desta página.
Com os melhores cumprimentos.
<EM ID="89" CATEG="PESSOA" TIPO="INDIVIDUAL">Eduardo Pereira</EM>
(<EM ID="90" CATEG="PESSOA" TIPO="CARGO">Presidente da Direcção</EM>)
NOTA:
Clique aqui ou na imagem do Quartel para continuar a navegar!
</DOC>
<DOC DOCID="HAREM-962-05111">
 HISTÓRICO Esta seção traz de volta um pouco da longa história do <EM ID="91" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">DCC</EM>.
O <EM ID="92" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">DCC</EM>- <EM ID="93" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Departamento de Cultura Científica do Centro Acadêmico Pereira Barretto</EM> (<EM ID="94" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">DCC/CAPB</EM>), órgão responsável pela representação e encaminhamento científico dos alunos da <EM ID="95" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">UNIFESP/EPM</EM>, fundado em <EM ID="96" CATEG="TEMPO" TIPO="DATA">1937</EM>, atua junto aos alunos promovendo vários cursos extracurriculares, palestras, conferências e discussões de interesse à área médica.
Organiza o <EM ID="97" CATEG="OUTRO">Prêmio "Pereira Barretto"</EM>, importante e conceituada premiação anual de trabalhos científicos acadêmicos, o <EM ID="98" CATEG="ACONTECIMENTO" TIPO="ORGANIZADO">Congresso Acadêmico Paulista de Medicina</EM> (<EM ID="99" CATEG="ACONTECIMENTO" TIPO="ORGANIZADO">CAPM</EM>), cursos de computação, cursos de idiomas e Revista científica.
<EM ID="100" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">DCC</EM> - Como começou Os alunos sempre estiveram envolvidos na estruturação da <EM ID="101" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Escola Paulista de Medicina</EM>.
Poucos anos após sua fundação as atividades estudantis se intensificaram.
O <EM ID="102" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">DCC</EM> surge em <ALT><EM ID="103" CATEG="TEMPO" TIPO="DATA">cinco de maio de 1937</EM>|cinco de <EM ID="104" CATEG="TEMPO" TIPO="DATA">maio de 1937</EM></ALT> graças ao apoio de professores e ao espirito virtuoso de acadêmicos que, no afã de realizar algo mais do que apenas seguir seus currículos, inauguraram uma história de trabalho, dedicação e abnegação.
Seus primeiros diretores foram os então acadêmicos <EM ID="105" CATEG="PESSOA" TIPO="INDIVIDUAL">Wladimir da Prússia Gomes Ferraz</EM> (<EM ID="106" CATEG="PESSOA" TIPO="CARGO">Presidente</EM>), <EM ID="107" CATEG="PESSOA" TIPO="INDIVIDUAL">Arulemo Santos Novaes</EM> e <EM ID="108" CATEG="PESSOA" TIPO="INDIVIDUAL">Jair Xavier Guimarães</EM> (<EM ID="109" CATEG="PESSOA" TIPO="GRUPOCARGO">Secretários</EM>).
O <EM ID="110" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">DCC/CAPB</EM> iniciou seus trabalhos coordenando atividades extracurriculares como Cursos, Congresso Acadêmico e instituindo Prêmios Científicos, como o <EM ID="111" CATEG="OUTRO">Prêmio Pereira Barreto</EM>, e organizando revista científica voltada para a divulgação de trabalhos produzidos por alunos da escola e por internos do <EM ID="112" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">Hospital São Paulo</EM>.
A revista foi denominada <EM ID="113" CATEG="ABSTRACCAO" TIPO="NOME">Medicina e Cultura</EM> e teve o seu primeiro número publicado em <EM ID="114" CATEG="TEMPO" TIPO="DATA">janeiro de 1939</EM>.
Atualmente, o <EM ID="115" CATEG="ORGANIZACAO" TIPO="INSTITUICAO">DCC</EM> organiza o <EM ID="116" CATEG="ACONTECIMENTO" TIPO="ORGANIZADO">Congresso Acadêmico Paulista de Medicina</EM>, o <EM ID="117" CATEG="OUTRO">Prêmio Pereira Barreto</EM> e, em média, <EM ID="118" CATEG="VALOR" TIPO="QUANTIDADE">20</EM> cursos de extensão universitária por ano, que contam com a presença de acadêmicos desta e demais instituições de ensino médico.
Temos aumentado a cada ano o reconhecimento de nossos cursos.
</DOC>
<DOC DOCID="HAREM-872-00971">
C o m p r a s .
.
.
 COMPRAS As melhores compras incluem os pulôveres das <EM ID="119" CATEG="LOCAL" TIPO="FISICO">Ilhas Aran</EM>, os produtos de lã ( jaquetas, coletes, boinas, chapéus, saias), os cristais de <EM ID="120" CATEG="LOCAL" TIPO="HUMANO">Waterford</EM>, as cerâmicas, o artesanato em linho e as jóias e bijuterias inspiradas nos desenhos do <EM ID="121" CATEG="OBRA" TIPO="REPRODUZIDA">Book of Kells</EM> e nos mitos celtas.
As plantas locais e a vida selvagem também são inspiração para essa arte.
O <EM ID="122" CATEG="LOCAL" TIPO="HUMANO">Condado de Galway</EM> produz o <EM ID="123" CATEG="COISA" TIPO="CLASSE">Claddagh</EM> ring "tradicional anel de noivado " feito em ouro, prata ou em pedras.
Os artefatos religiosos também valem ser destacados.
Ler é uma paixão nacional, portanto existem excelentes livrarias.
Em <EM ID="124" CATEG="LOCAL" TIPO="HUMANO">Dublin</EM>, a maior é a <EM ID="125" CATEG="ORGANIZACAO" TIPO="EMPRESA">Eason and Son</EM>,que tem uma variedade enorme da literatura irlandesa.
Os instrumentos musicais são feitos em várias regiões, mas o <EM ID="126" CATEG="LOCAL" TIPO="HUMANO">Condado de Clare</EM> é conhecido como "the singing county".
As harpas são especialmente feitas em <EM ID="127" CATEG="LOCAL" TIPO="HUMANO">Dublin</EM> e <EM ID="128" CATEG="LOCAL" TIPO="HUMANO">Mayo</EM>.
Nào poderia esquecer, é claro do whiskey e de algumas guloseimas como as algas marinhas secas, que são comidas cruas ou misturadas na comida.
Em <EM ID="129" CATEG="LOCAL" TIPO="HUMANO">Dublin</EM> passeie no shopping <OMITIDO><EM ID="130" CATEG="LOCAL" TIPO="HUMANO">St. Stephen's Green</EM></OMITIDO>, na <EM ID="131" CATEG="LOCAL" TIPO="HUMANO">Grafton Street</EM> e na a <OMITIDO><EM ID="132" CATEG="LOCAL" TIPO="HUMANO">O'Connell Street</EM></OMITIDO>.
Tem muitas lojas para apreciar.
Em <EM ID="133" CATEG="LOCAL" TIPO="HUMANO">Waterford</EM>, visite a fábrica de cristais <EM ID="134" CATEG="ORGANIZACAO" TIPO="EMPRESA">Waterford</EM> (<EM ID="135" CATEG="ORGANIZACAO" TIPO="EMPRESA">Waterford Crystal Factory</EM>), que foi fundada em <EM ID="136" CATEG="TEMPO" TIPO="DATA">1783</EM> e fica a <EM ID="137" CATEG="VALOR" TIPO="QUANTIDADE">2,5 km</EM> ao sul do centro da cidade.
Você verá o processo de fabricação das peças.
O linho irlandês é famoso no mundo todo e de alcance inigualado.
Há uma variedade enorme que inclui colchas extravagantes, toalhas de mesa encaracoladas, guardanapos, etc. Enfeites em linho com finos entrelaços estão por toda a <EM ID="138" CATEG="LOCAL" TIPO="HUMANO">Irlanda</EM>, mas principalmente em <EM ID="139" CATEG="LOCAL" TIPO="HUMANO">Limerick</EM> e <EM ID="140" CATEG="LOCAL" TIPO="HUMANO">Kenmare</EM>.
</DOC>
<DOC DOCID="HAREM-273-02298">
Empates na <EM ID="141" CATEG="ACONTECIMENTO" TIPO="ORGANIZADO">Honra</EM>
O <ALT><EM ID="142" CATEG="ACONTECIMENTO" TIPO="EVENTO">Ovarense-Amora</EM>|<EM ID="143" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Ovarense</EM>-<EM ID="144" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Amora</EM></ALT> e o <ALT><EM ID="145" CATEG="ACONTECIMENTO" TIPO="EVENTO">Nacional-Académica</EM>|<EM ID="146" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Nacional</EM>-<EM ID="147" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Académica</EM></ALT>, dois jogos da <EM ID="148" CATEG="ACONTECIMENTO" TIPO="EVENTO">26ª jornada da II Divisão de Honra</EM> antecipados para ontem, terminaram empatados. Em <EM ID="149" CATEG="LOCAL" TIPO="HUMANO">Ovar</EM>, a equipa da casa esteve mesmo a perder com o <EM ID="150" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Amora</EM>, quando um erro defensivo permitiu a <EM ID="151" CATEG="PESSOA" TIPO="INDIVIDUAL">Rui Maside</EM> inaugurar o marcador (<EM ID="152" CATEG="VALOR" TIPO="QUANTIDADE">14'</EM>). A <EM ID="153" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Ovarense</EM> atacava mais, mas só aos <EM ID="154" CATEG="VALOR" TIPO="QUANTIDADE">64'</EM> conseguiu marcar, por <EM ID="155" CATEG="PESSOA" TIPO="INDIVIDUAL">Emanuel</EM>, que de cabeça concluiu um canto marcado por <EM ID="156" CATEG="PESSOA" TIPO="INDIVIDUAL">Quinito</EM>. O <EM ID="157" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Amora</EM> teve dois expulsos -- <EM ID="158" CATEG="PESSOA" TIPO="INDIVIDUAL">João Paulo</EM> (<EM ID="159" CATEG="VALOR" TIPO="QUANTIDADE">56'</EM>) e <EM ID="160" CATEG="PESSOA" TIPO="INDIVIDUAL">Gil</EM> (<EM ID="161" CATEG="VALOR" TIPO="QUANTIDADE">72'</EM>) -- mas manteve o empate até ao final. Na <EM ID="162" CATEG="LOCAL" TIPO="HUMANO">Madeira</EM>, o <EM ID="163" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Nacional</EM> empatou a zero com a <EM ID="164" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Académica</EM> num jogo fraco e onde o calor foi o dado mais assinalável. A <EM ID="165" CATEG="VALOR" TIPO="CLASSIFICACAO">26ª</EM> jornada ficará completa hoje com os seguintes jogos: <ALT><EM ID="166" CATEG="ACONTECIMENTO" TIPO="EVENTO">Penafiel-Rio Ave</EM>|<EM ID="167" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Penafiel</EM>-<EM ID="168" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Rio Ave</EM></ALT>, <ALT><EM ID="169" CATEG="ACONTECIMENTO" TIPO="EVENTO">Famalicão-Espinho</EM>|<EM ID="170" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Famalicão</EM>-<EM ID="171" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Espinho</EM></ALT>, <ALT><EM ID="172" CATEG="ACONTECIMENTO" TIPO="EVENTO">Portimonense-Estoril</EM>|<EM ID="173" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Portimonense</EM>-<EM ID="174" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Estoril</EM></ALT>, <ALT><EM ID="175" CATEG="ACONTECIMENTO" TIPO="EVENTO">Torreense-Leça</EM>|<EM ID="176" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Torreense</EM>-<EM ID="177" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Leça</EM></ALT>, <ALT><EM ID="178" CATEG="ACONTECIMENTO" TIPO="EVENTO">Feirense-Felgueiras</EM>|<EM ID="179" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Feirense</EM>-<EM ID="180" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Felgueiras</EM></ALT>, <ALT><EM ID="181" CATEG="ACONTECIMENTO" TIPO="EVENTO">União Lamas-Paços Ferreira</EM>|<EM ID="182" CATEG="PESSOA" TIPO="GRUPOMEMBRO">União Lamas</EM>-<EM ID="183" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Paços Ferreira</EM></ALT> e <ALT><EM ID="184" CATEG="ACONTECIMENTO" TIPO="EVENTO">Aves-Campomaiorense</EM>|<EM ID="185" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Aves</EM>-<EM ID="186" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Campomaiorense</EM></ALT>
<EM ID="187" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Bremen</EM> à frente
O <EM ID="188" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Werder Bremen</EM> já alcançou o <EM ID="189" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Borussia Dortmund</EM> no primeiro lugar do campeonato alemão de futebol, tendo anteontem vencido o <EM ID="190" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Duisburg</EM> por <EM ID="191" CATEG="VALOR" TIPO="CLASSIFICACAO">5-1</EM> e beneficiado do empate (<EM ID="192" CATEG="VALOR" TIPO="CLASSIFICACAO">0-0</EM>) cedido pelo <EM ID="193" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Borussia</EM> na deslocação a <EM ID="194" CATEG="LOCAL" TIPO="HUMANO">Estugarda</EM>. O <EM ID="195" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Werder Bremen</EM> abriu o marcador logo aos <EM ID="196" CATEG="VALOR" TIPO="QUANTIDADE">18'</EM> pelo líbero egípcio <EM ID="197" CATEG="PESSOA" TIPO="INDIVIDUAL">Hany Ramzy</EM> e chegou ao intervalo a ganhar por <EM ID="198" CATEG="VALOR" TIPO="CLASSIFICACAO">3-0</EM>, com golos de <EM ID="199" CATEG="PESSOA" TIPO="INDIVIDUAL">Mario Basler</EM> (<EM ID="200" CATEG="VALOR" TIPO="QUANTIDADE">24'</EM>) e <EM ID="201" CATEG="PESSOA" TIPO="INDIVIDUAL">Bernd Hobsch</EM> (<EM ID="202" CATEG="VALOR" TIPO="QUANTIDADE">36'</EM>). <EM ID="203" CATEG="PESSOA" TIPO="INDIVIDUAL">Marco Bode</EM> fez o <EM ID="204" CATEG="VALOR" TIPO="CLASSIFICACAO">4-0</EM> aos<EM ID="205" CATEG="VALOR" TIPO="QUANTIDADE">67'</EM>, o <EM ID="206" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Duisburg</EM> reduziu por <EM ID="207" CATEG="PESSOA" TIPO="INDIVIDUAL">Markkus Marin</EM> (<EM ID="208" CATEG="VALOR" TIPO="QUANTIDADE">78'</EM>) e foi <EM ID="209" CATEG="PESSOA" TIPO="INDIVIDUAL">Andreas Herzog</EM> quem estabeleceu o resultado final, a sete minutos do fim. Sem poder contar com <EM ID="210" CATEG="PESSOA" TIPO="INDIVIDUAL">Stephane Chapuisat</EM>, <EM ID="211" CATEG="PESSOA" TIPO="INDIVIDUAL">Steffen Freund</EM> e <EM ID="212" CATEG="PESSOA" TIPO="INDIVIDUAL">Matthias Sammer</EM>, o <EM ID="213" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Borussia</EM> não foi ontem além de um empate a zero em <EM ID="214" CATEG="LOCAL" TIPO="HUMANO">Estugarda</EM>, onde só ganhou uma vez nos últimos <EM ID="215" CATEG="VALOR" TIPO="QUANTIDADE">12 anos</EM>. O <EM ID="216" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Borussia Moenchengladbach</EM>, que venceu em <EM ID="217" CATEG="LOCAL" TIPO="HUMANO">Bochum</EM> por <EM ID="218" CATEG="VALOR" TIPO="CLASSIFICACAO">2-0</EM> (golos de <EM ID="219" CATEG="PESSOA" TIPO="INDIVIDUAL">Thomas Kastenmaier</EM> e <EM ID="220" CATEG="PESSOA" TIPO="INDIVIDUAL">Heiko Herrlich</EM>), e o <EM ID="221" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Kaiserslautern</EM>, que derrotou o <EM ID="222" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Schalke</EM> por <EM ID="223" CATEG="VALOR" TIPO="CLASSIFICACAO">1-0</EM> (golo de <EM ID="224" CATEG="PESSOA" TIPO="INDIVIDUAL">Steffan Kuntz</EM>) aproximaram-se dos líderes, estando agora a apenas dois pontos. Eis os resultados da <EM ID="225" CATEG="VALOR" TIPO="CLASSIFICACAO">23ª</EM> jornada: <ALT><EM ID="226" CATEG="ACONTECIMENTO" TIPO="EVENTO">Werder Bremen-Duisburg</EM>|<EM ID="227" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Werder Bremen</EM>-<EM ID="228" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Duisburg</EM></ALT>, <EM ID="229" CATEG="VALOR" TIPO="CLASSIFICACAO">5-1</EM>; <ALT><EM ID="230" CATEG="ACONTECIMENTO" TIPO="EVENTO">Estugarda-Borussia Dortmund</EM>|<EM ID="231" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Estugarda</EM>-<EM ID="232" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Borussia Dortmund</EM></ALT>, <EM ID="233" CATEG="VALOR" TIPO="CLASSIFICACAO">0-0</EM>; <ALT><EM ID="234" CATEG="ACONTECIMENTO" TIPO="EVENTO">Bochum-Borussia M'Gladbach</EM>|<EM ID="235" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Bochum</EM>-<EM ID="236" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Borussia M'Gladbach</EM></ALT>, <EM ID="237" CATEG="VALOR" TIPO="CLASSIFICACAO">0-2</EM>; <ALT><EM ID="238" CATEG="ACONTECIMENTO" TIPO="EVENTO">Dynamo Dresden-Hamburgo</EM>|<EM ID="239" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Dynamo Dresden</EM>-<EM ID="240" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Hamburgo</EM></ALT>, <EM ID="241" CATEG="VALOR" TIPO="CLASSIFICACAO">1-1</EM>; <ALT><EM ID="242" CATEG="ACONTECIMENTO" TIPO="EVENTO">Bayern Munique-TSV Munique</EM>|<EM ID="243" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Bayern Munique</EM>-<EM ID="244" CATEG="PESSOA" TIPO="GRUPOMEMBRO">TSV Munique</EM></ALT>, <EM ID="245" CATEG="VALOR" TIPO="CLASSIFICACAO">1-0</EM>; <ALT><EM ID="246" CATEG="ACONTECIMENTO" TIPO="EVENTO">Schalke-Kaiserslautern</EM>|<EM ID="247" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Schalke</EM>-<EM ID="248" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Kaiserslautern</EM></ALT>, <EM ID="249" CATEG="VALOR" TIPO="CLASSIFICACAO">0-1</EM>; <ALT><EM ID="250" CATEG="ACONTECIMENTO" TIPO="EVENTO">Bayer Uerdingen-Eintracht Frankfurt</EM>|<EM ID="251" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Bayer Uerdingen</EM>-<EM ID="252" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Eintracht Frankfurt</EM></ALT>, <EM ID="253" CATEG="VALOR" TIPO="CLASSIFICACAO">1-1</EM>;<ALT><EM ID="254" CATEG="ACONTECIMENTO" TIPO="EVENTO">Bayer Leverkusen-Freiburg</EM>|<EM ID="255" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Bayer Leverkusen</EM>-<EM ID="256" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Freiburg</EM></ALT>, <EM ID="257" CATEG="VALOR" TIPO="CLASSIFICACAO">2-4</EM>; <ALT><EM ID="258" CATEG="ACONTECIMENTO" TIPO="EVENTO">Karlsruher-Colónia</EM>|<EM ID="259" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Karlsruher</EM>-<EM ID="260" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Colónia</EM></ALT>, <EM ID="261" CATEG="VALOR" TIPO="CLASSIFICACAO">0-0</EM>. Classificação após <EM ID="262" CATEG="VALOR" TIPO="QUANTIDADE">23</EM> jogos: <EM ID="263" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Borussia Dortmund</EM> e <EM ID="264" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Werder Bremen</EM>, <EM ID="265" CATEG="VALOR" TIPO="CLASSIFICACAO">34 pontos</EM>; <EM ID="266" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Borussia Moenchengladbach</EM> e <EM ID="267" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Kaiserslautern</EM>, <EM ID="268" CATEG="VALOR" TIPO="CLASSIFICACAO">32</EM>; <EM ID="269" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Freiburg</EM> e <EM ID="270" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Bayern Munique</EM>, <EM ID="271" CATEG="VALOR" TIPO="CLASSIFICACAO">30</EM>; <EM ID="272" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Karlsruher</EM>, <EM ID="273" CATEG="VALOR" TIPO="CLASSIFICACAO">25</EM>; <EM ID="274" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Bayer Leverkusen</EM>, <EM ID="275" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Hamburgo</EM> e <EM ID="276" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Estugarda</EM>, <EM ID="277" CATEG="VALOR" TIPO="CLASSIFICACAO">22</EM>; <EM ID="278" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Colónia</EM> e <EM ID="279" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Eintracht Frankfurt</EM>, <EM ID="280" CATEG="VALOR" TIPO="CLASSIFICACAO">21</EM>; <EM ID="281" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Schalke</EM>, <EM ID="282" CATEG="VALOR" TIPO="CLASSIFICACAO">20</EM>; <EM ID="283" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Bayer Uerdingen</EM>, <EM ID="284" CATEG="VALOR" TIPO="CLASSIFICACAO">16</EM>; <EM ID="285" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Bochum</EM> e <EM ID="286" CATEG="PESSOA" TIPO="GRUPOMEMBRO">TSV Munique</EM>, <EM ID="287" CATEG="VALOR" TIPO="CLASSIFICACAO">14</EM>; <EM ID="288" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Duisburg</EM>, <EM ID="289" CATEG="VALOR" TIPO="CLASSIFICACAO">13</EM>; <EM ID="290" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Dynamo Dresden</EM>, <EM ID="291" CATEG="VALOR" TIPO="CLASSIFICACAO">12</EM>.
<EM ID="292" CATEG="LOCAL" TIPO="HUMANO">França</EM> teve <EM ID="293" CATEG="ACONTECIMENTO" TIPO="ORGANIZADO">Taça</EM>
O <EM ID="294" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Paris St. Germain</EM> e o <EM ID="295" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Bastia</EM> ficaram ontem apurados para a final da <EM ID="296" CATEG="ACONTECIMENTO" TIPO="ORGANIZADO">Taça da Liga de França</EM>, em futebol. A equipa parisiense venceu fora o <EM ID="297" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Le Havre</EM>, com um golo de <EM ID="298" CATEG="PESSOA" TIPO="INDIVIDUAL">Raí</EM> na conversão de um penalti, e defrontará na final o <EM ID="299" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Bastia</EM>, que derrotou na <EM ID="300" CATEG="LOCAL" TIPO="HUMANO">Córsega</EM> o <EM ID="301" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Montpellier</EM> por <EM ID="302" CATEG="VALOR" TIPO="CLASSIFICACAO">3-1</EM>. O <EM ID="303" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Bastia</EM> marcou primeiro, por <EM ID="304" CATEG="PESSOA" TIPO="INDIVIDUAL">Bruno Rodriguez</EM> (<EM ID="305" CATEG="VALOR" TIPO="QUANTIDADE">43'</EM>), mas <EM ID="306" CATEG="PESSOA" TIPO="INDIVIDUAL">Thierry Laurey</EM> chegou ao empate seis minutos depois. E só nos últimos dez minutos o <EM ID="307" CATEG="PESSOA" TIPO="GRUPOMEMBRO">Bastia</EM> assegurou a presença na final, com dois golos de <EM ID="308" CATEG="PESSOA" TIPO="INDIVIDUAL">Franck Burnier</EM> (<EM ID="309" CATEG="VALOR" TIPO="QUANTIDADE">82'</EM>) e <EM ID="310" CATEG="PESSOA" TIPO="INDIVIDUAL">Anton Drobnjak</EM> (<EM ID="311" CATEG="VALOR" TIPO="QUANTIDADE">88'</EM>). O vencedor da <EM ID="312" CATEG="ACONTECIMENTO" TIPO="ORGANIZADO">Taça da Liga</EM> terá direito a estar presente na <EM ID="313" CATEG="ACONTECIMENTO" TIPO="ORGANIZADO">Taça UEFA</EM> da próxima época.
</DOC>
<DOC DOCID="HAREM-654-09451">
<EM ID="314" CATEG="PESSOA" TIPO="INDIVIDUAL">Lula</EM> declarou admirar <EM ID="315" CATEG="PESSOA" TIPO="INDIVIDUAL">Hitler</EM> e <EM ID="316" CATEG="PESSOA" TIPO="INDIVIDUAL">Khomeini</EM> 